# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

    # Generates the snake  
- uses: Platane/snk@v3
  with:
    github_user_name: ${{ github.repository_owner }}
    outputs: |
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark
      dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
# show the status of the build. Makes it easier for debugging (if there's any issues).
- run: git status
