name: Snake generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" #  run every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create snake
        uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}
          svg: snake.svg


      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
